---
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - default.yml

- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- include: debian.yml
  when: ansible_os_family == 'Debian'

- name: create filebeat.yml for controller
  copy: src=controller.yml dest=/etc/filebeat/filebeat.yml
  when: "'controller' in group_names"
  notify:
    - restart filebeat

- name: create filebeat.yml for compute
  copy: src=compute.yml dest=/etc/filebeat/filebeat.yml
  when: "'compute' in group_names"
  notify:
    - restart filebeat

- name: flush handlers to prevent start then restart
  meta: flush_handlers

- name: start and enable filebeat
  service:
    name: filebeat
    state: started
    enabled: true
