---
- name: add rpm key for elastic.co
  rpm_key:
    key: "{{ filebeat_gpg_url }}"

- name: Add filebeat repository
  template: src=filebeat.repo dest=/etc/yum.repos.d/elastic-beats.repo

- name: install filebeat
  yum:
    name: filebeat
    state: present
  notify:
    - restart filebeat
